//Introduction to Output Components

/*
* Visualforce includes nearly 150 built-in components that you can use on your pages. Components are rendered into HTML
* CSS, and JavaScript when a page is requested. Coarse-grained components provide a significant amount of functionality in
* a single component, and might add a lot of information and user interface to the page it’s used on. Fine-grained
* components provide more focused functionality, and enable you to design the page to look and behave the way you want.
* Here we’ll focus on output components, that is, components that output data from a record and enable you to design a
* view-only user interface.
*/